import { Montserrat } from "next/font/google" // Import the Montserrat font
import "./globals.css"
import Navbar from "@/components/Navbar"

// Import the Montserrat Subrayada font with specific settings
const montserratSubrayada = Montserrat({
  weight: "400", // You can change the weight as needed
  style: "normal",
  subsets: ["latin"],
  variable: "--font-montserrat-subrayada", // Custom CSS variable for this font
})

export const metadata = {
  title: "Wiki",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserratSubrayada.variable} antialiased `}>
        <div className="flex flex-col items-center  justify-center">
          <div className="max-w-full bg-stone-100 sm:max-w-md md:max-w-2xl lg:max-w-4xl mx-auto border my-8 shadow-md rounded-2xl p-6 w-full">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
